name: Test_workflow
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:
env:
  password: ${{ secrets.PASSWORD }}

jobs:
  job1-run_py_file:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Run a python file
        run: |
          cd scripts
          python hello.py
        # run: python hello.py
        # working-directory: ./scripts

  job2-secret:
    # needs: job1-run_py_file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a line
        run: echo "This is a file with password $password"

  job3_dependency:
    needs: [job1-run_py_file,job2-secret]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a line
        run: echo "This is a file with password $password"

  job4_if_dependency:
    if: ${{ always() }}
    needs: job1-run_py_file
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a line
        run: echo "This is a file with password $password"

        